version: '3.9'
services:
  lojaweb:
    image: python:3.11-slim
    container_name: lojaweb
    working_dir: /app
    command: sh -c "pip install --no-cache-dir -r requirements.txt && python app.py"
    volumes:
      - ./:/app
      - lojaweb_data:/app/instance
    ports:
      - "5000:5000"
    restart: unless-stopped
    environment:
      - FLASK_ENV=production

volumes:
  lojaweb_data:
